### ISSUE TITLE
Client just gives errors when executing any command

### ISSUE THREAD

**Issue by CommanderRedYT** [UserBlackBox/octoprint-cli#17]
**Describe the bug**
I don't even know what it is... And sorry for the title...

I tried  `octoprint-cli system restart` and other commands, and this happened:

```python3
ccomm@Sobotka:~$ octoprint-cli system restart
Traceback (most recent call last):
  File "/home/ccomm/.local/lib/python3.8/site-packages/octoprint_cli/__main__.py", line 639, in main
    if config['preferences']['UpdateCheck'] == 'true':
  File "/usr/lib/python3.8/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'UpdateCheck'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ccomm/.local/bin/octoprint-cli", line 8, in <module>
    sys.exit(main())
  File "/home/ccomm/.local/lib/python3.8/site-packages/octoprint_cli/__main__.py", line 642, in main
    updateCheck()
  File "/home/ccomm/.local/lib/python3.8/site-packages/octoprint_cli/__main__.py", line 635, in updateCheck
    if v(request.json()['tag_name'][1:]) > v(__version__):
  File "/home/ccomm/.local/lib/python3.8/site-packages/octoprint_cli/__main__.py", line 634, in <lambda>
    v = lambda t: tuple(map(int,t.split('.')))
ValueError: invalid literal for int() with base 10: '1-1'
```

**Additional context**
The only thing that worked was the command syntax (for example `octoprint-cli -h`)

**Comment by UserBlackBox** [comment]
Should be fixed as of [v3.2.2](https://github.com/UserBlackBox/octoprint-cli/releases/tag/v3.2.2)

Can be updated with `pip install --upgrade octoprint-cli`
